### ISSUE TITLE
Duplicate Raw in HttpDuplex

### ISSUE THREAD

**Issue by scorsi** [kiwixz/sza#10]
You should document (or think about) the usage of the duplicate `Net::Raw` in the `HttpDuplex` because I really don't understand and the PR's discution is discontinuated.
- `HttpDuplex->raw_req` with `HttpDuplex->req->body`
- `HttpDuplex->raw_resp` with `HttpDuplex->resp->body`.

**Comment by PierreBougon** [comment]
I'm not sure it works that way. `HttpDuplex->raw_req` seems to be the param we receive from network and `HttpDuplex->raw_resp` the response we give to network.

I really don't like the fact the data is duplacted into the same structure or I have misunderstood something due to the lack of documentation.

**Comment by kiwixz** [comment]
As explained on #2, the request/response is the body plus the headers, so it is not a strict duplication.

**Comment by scorsi** [comment]
As my last question has never been answered, I reask here to be sure.
