### ISSUE TITLE
copy of std::vector

### ISSUE THREAD

**Issue by polosskevin** [kiwixz/sza#4]
Could we please avoid unnecessary copy in the api please ?
Is there a particular reason ?
```c++
 /**
        * Send a response.
        * \return true on success, otherwise false
        */
        virtual bool send(ImplSocket* sock, Raw resp) = 0;
```
possible fix:
```c++
        virtual bool send(ImplSocket* sock, Raw const & resp) = 0;
```

**Comment by kiwixz** [comment]
Fixed (with const on the correct side).

**Comment by Stargateur** [comment]
@kiwixz Sorry, the position of `const` in `Raw const & resp` is perfectly valid and better. Put `const` on the left is a sugar syntax. Type qualifiers apply to the left, but when there is nothing on the left, compiler apply it to the right. http://en.cppreference.com/w/cpp/language/cv

`const char const *ptr` will not compile but `const char * const ptr` will, that why some people prefer to always put it in the right `char const * const ptr` to be consistent.

**Comment by polosskevin** [comment]
Exactly : )

**Comment by kiwixz** [comment]
@Stargateur [isocpp guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rl-const) recommend this conventional notation, but above all we need **consistency**.

**Comment by Stargateur** [comment]
@kiwixz https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#nl-naming-and-layout-rules. 
>Most of these rules are aesthetic and programmers hold strong opinions. IDEs also tend to have defaults and a range of alternatives. These rules are suggested defaults to follow unless you have reasons not to.

No more to say except that "tradition" is not a good argument. Your own link clearly say "We are well aware that you could claim the "bad" examples more logical than the ones marked "OK", but they also confuse more people, especially novices relying on teaching material using the far more common, conventional OK style.". Do I really need to explain why it's stupid to continue bad practice because we have always do that ?

**Comment by kiwixz** [comment]
What you can do is not always what you should do.
It is **NOT** more consistent. Consistency is only about this codebase.
